server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/dboasis
    username: system_app
    password: 855312
#  mvc:
#    static-path-pattern=/static/**

email:
  recipient: ${MAIL_APP}
  password: ${MAIL_PASSWORD_APP}

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw