server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/dboasis
    username: system_app
    password: 855312

email:
  recipient: ${MAIL_APP}
  password: ${MAIL_PASSWORD_APP}

app:
  jwt:
    secret: ${SECRET_KEY}